# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainframe.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 450, 550))
        self.tabWidget.setObjectName("tabWidget")
        self.main = QtWidgets.QWidget()
        self.main.setObjectName("main")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.main)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 421, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnStatus1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnStatus1.setObjectName("btnStatus1")
        self.verticalLayout.addWidget(self.btnStatus1)
        self.btnStatus2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnStatus2.setObjectName("btnStatus2")
        self.verticalLayout.addWidget(self.btnStatus2)
        self.btnStatus3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnStatus3.setObjectName("btnStatus3")
        self.verticalLayout.addWidget(self.btnStatus3)
        self.btnStatus4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnStatus4.setObjectName("btnStatus4")
        self.verticalLayout.addWidget(self.btnStatus4)
        self.tabWidget.addTab(self.main, "")
        self.overview = QtWidgets.QWidget()
        self.overview.setObjectName("overview")
        self.tabWidget.addTab(self.overview, "")
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.tabWidget.addTab(self.settings, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Zeiterfassung"))
        self.btnStatus1.setText(_translate("Dialog", "Status 1"))
        self.btnStatus2.setText(_translate("Dialog", "Status 2"))
        self.btnStatus3.setText(_translate("Dialog", "Status 3"))
        self.btnStatus4.setText(_translate("Dialog", "Status 4"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main), _translate("Dialog", "Status"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.overview), _translate("Dialog", "Übersicht"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), _translate("Dialog", "Einstellungen"))


def run(name1, name2, name3, name4):
    app = QtWidgets.QApplication([])
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    ui.btnStatus1.setText(name1)
    ui.btnStatus2.setText(name2)
    ui.btnStatus3.setText(name3)
    ui.btnStatus4.setText(name4)
    Dialog.show()
    sys.exit(app.exec_())
